Neste notebook, será implementado o algoritmo de treinamento do Perceptron.

In [1]:
import numpy as np
import pandas as pd
from Perceptron import Perceptron
from Activation import Degree

# Dataset

O arquivo de exemplos utilizado será 'data1.txt', conforme o cálculo do identificador da equipe a seguir:

I. $matA + matB + matC + matD = 17$

II. $17 \bmod 4 = 1$


In [2]:
examples = 'data/dataAll.txt'
nparray = np.fromfile(examples)
nparray

array([-363.7884,  244.1423,    0.    , ..., -140.147 ,  734.0983,
          0.    ], shape=(3000,))

In [3]:
# Formatando o array de entrada
data = nparray.reshape(1000,3)
data

array([[-363.7884,  244.1423,    0.    ],
       [ 328.7572, -256.7658,    1.    ],
       [-164.9827,  613.2164,    0.    ],
       ...,
       [ 872.4311,  669.1192,    1.    ],
       [ 822.6894, -702.6489,    1.    ],
       [-140.147 ,  734.0983,    0.    ]], shape=(1000, 3))

In [4]:
X = data[:, :2]
y = data[:, 2]

print(f'X: {X[:5]}\n')
print(f'Y: {y[:5]}')

X: [[-363.7884  244.1423]
 [ 328.7572 -256.7658]
 [-164.9827  613.2164]
 [ 536.5905  764.9575]
 [ 314.2297  343.8375]]

Y: [0. 1. 0. 0. 0.]


In [5]:
p= Perceptron()
activation= Degree()

x = np.insert(X, 0, 1, axis=1) # inserindo o viés

epoch= 0
convergence= False
adjusts = 0

while not convergence:
    convergence = True
    

    for i in range(len(X)):
        u = np.dot(x[i], p.w)

        y_predicted = activation.f(u)
        error = y[i] - y_predicted
        
        
        if error != 0:
            convergence = False
            p.w = p.w + p.learning_rate * error * x[i]
            print(p.w)
            adjusts += 1
        

    epoch += 1

print(f'Convergência em {epoch} épocas')
print(f'{adjusts} ajustes feitos')

Erro 1 ou -1
[ -0.52613745  36.06385425 -24.27880182]
Erro 1 ou -1
[  -0.62613745  -17.59519575 -100.77455182]
Erro 1 ou -1
[ -0.52613745  55.20082425 -64.94499182]
Erro 1 ou -1
[ -0.42613745 137.79952425  14.91083818]
Erro 1 ou -1
[ -0.52613745 143.64528425 -63.38375182]
Erro 1 ou -1
[  -0.62613745  103.63637425 -141.27644182]
Erro 1 ou -1
[ -0.72613745 157.30618425 -92.18417182]
Erro 1 ou -1
[  -0.62613745  104.34612425 -149.05363182]
Erro 1 ou -1
[ -0.72613745 163.90564425 -98.93130182]
Erro 1 ou -1
[  -0.62613745  118.38101425 -164.56723182]
Erro 1 ou -1
[ -0.72613745 209.09687425 -89.85391182]
Erro 1 ou -1
[  -0.62613745  151.31588425 -150.16206182]
Erro 1 ou -1
[  -0.52613745  103.04932425 -198.63178182]
Erro 1 ou -1
[  -0.42613745  173.49667425 -156.51551182]
Erro 1 ou -1
[  -0.32613745  126.65467425 -207.92538182]
Erro 1 ou -1
[  -0.22613745  196.51830425 -143.70644182]
Erro 1 ou -1
[  -0.32613745  140.68257425 -199.88397182]
Erro 1 ou -1
[  -0.22613745  217.67004425 -135.03464