Neste notebook, será implementado o algoritmo de treinamento do Perceptron.

In [1]:
import numpy as np
import pandas as pd
from Perceptron import Perceptron
from Activation import Degree

# Dataset

O arquivo de exemplos utilizado será 'data1.txt', conforme o cálculo do identificador da equipe a seguir:

I. $matA + matB + matC + matD = 17$

II. $17 \bmod 4 = 1$


In [2]:
examples = 'data/dataAll.txt'
examplesHoldout = 'data/dataHoldout.txt'
nparray = np.fromfile(examples)
hlarray = np.fromfile(examplesHoldout)

nparray, hlarray

(array([-363.7884,  244.1423,    0.    , ..., -140.147 ,  734.0983,
           0.    ], shape=(3000,)),
 array([-0.29322959, -0.09065359,  1.        , ...,  0.72930655,
         0.93224271,  0.        ], shape=(2400,)))

In [3]:
# Formatando o array de entrada
data = nparray.reshape(1000,3)
dataHoldout = hlarray.reshape(800,3)
data, dataHoldout

(array([[-363.7884,  244.1423,    0.    ],
        [ 328.7572, -256.7658,    1.    ],
        [-164.9827,  613.2164,    0.    ],
        ...,
        [ 872.4311,  669.1192,    1.    ],
        [ 822.6894, -702.6489,    1.    ],
        [-140.147 ,  734.0983,    0.    ]], shape=(1000, 3)),
 array([[-0.29322959, -0.09065359,  1.        ],
        [ 0.07988839,  0.21101297,  1.        ],
        [-0.07825563, -0.08083512,  1.        ],
        ...,
        [ 0.65980493,  1.05876739,  0.        ],
        [ 1.09867123,  0.87404891,  0.        ],
        [ 0.72930655,  0.93224271,  0.        ]], shape=(800, 3)))

In [4]:
X = data[:, :2]
y = data[:, 2]

print(f'X: {X[:5]}\n')
print(f'Y: {y[:5]}')

X: [[-363.7884  244.1423]
 [ 328.7572 -256.7658]
 [-164.9827  613.2164]
 [ 536.5905  764.9575]
 [ 314.2297  343.8375]]

Y: [0. 1. 0. 0. 0.]


In [5]:
p= Perceptron()
activation= Degree()

x = np.insert(X, 0, 1, axis=1) # inserindo o viés

epoch= 0
convergence= False
adjusts = 0

while not convergence:
    convergence = True
    

    for i in range(len(X)):
        u = np.dot(x[i], p.w)

        y_predicted = activation.f(u)
        error = y[i] - y_predicted
        
        
        if error != 0:
            convergence = False
            p.w = p.w + p.learning_rate * error * x[i]
            print(p.w)
            adjusts += 1
        

    epoch += 1

print(f'Convergência em {epoch} épocas')
print(f'{adjusts} ajustes feitos')

[ -0.20997318  36.12338879 -24.61167692]
[  -0.30997318  -17.53566121 -101.10742692]
[ -0.20997318  55.26035879 -65.27786692]
[-1.09973185e-01  1.37859059e+02  1.45779631e+01]
[ -0.20997318 143.70481879 -63.71662692]
[  -0.30997318  103.69590879 -141.60931692]
[ -0.40997318 157.36571879 -92.51704692]
[  -0.30997318  104.40565879 -149.38650692]
[ -0.40997318 163.96517879 -99.26417692]
[  -0.30997318  118.44054879 -164.90010692]
[ -0.40997318 209.15640879 -90.18678692]
[  -0.30997318  151.37541879 -150.49493692]
[  -0.20997318  103.10885879 -198.96465692]
[-1.09973185e-01  1.73556209e+02 -1.56848387e+02]
[-9.97318462e-03  1.26714209e+02 -2.08258257e+02]
[ 9.00268154e-02  1.96577839e+02 -1.44039317e+02]
[-9.97318462e-03  1.40742109e+02 -2.00216847e+02]
[ 9.00268154e-02  2.17729579e+02 -1.35367517e+02]
[   0.19002682  181.45953879 -178.59555692]
[ 9.00268154e-02  1.63220399e+02 -1.96929197e+02]
[ 1.90026815e-01  2.38642839e+02 -1.30874087e+02]
[   0.29002682  174.28370879 -213.29652692]
[ 

Validação Holdout em Problema Não-Linearmente Separável

In [6]:
Xh = dataHoldout[:, :2]
yh = dataHoldout[:, 2]

In [7]:
np.random.seed(1)
index = np.random.permutation(len(dataHoldout)) # shuffle nos dados
split_index = int(0.7 * len(dataHoldout)) #split no 70/30

In [8]:
train_index = index[:split_index]
test_index = index[split_index:]

train_data = dataHoldout[train_index]
test_data = dataHoldout[test_index]

In [9]:
Xh_train = train_data[:, :2]
yh_train = train_data[:, 2]

Xh_test = test_data[:, :2]
yh_test = test_data[:, 2]


Treinando o Perceptron (Validação Holdout)

In [10]:
xh_train = np.insert(Xh_train, 0, 1, axis=1)

holdoutAdjusts = 0
max_epochs = 100

for epoch in range(max_epochs):
    index = np.random.permutation(len(xh_train))
    xh_train_permuted = xh_train[index]
    yh_train_permuted = yh_train[index]

    for i in range(len(xh_train)):
        u = np.dot(xh_train_permuted[i], p.w)
        yh_predicted = activation.f(u)
        error = yh_train_permuted[i] - yh_predicted

        if error != 0:
            p.w = p.w + p.learning_rate * error * xh_train_permuted[i]
            holdoutAdjusts += 1

    print(f'Época {epoch + 1} finalizada. Pesos: {p.w}')

print(f'Pesos: {p.w}')
print(f'Total de ajustes: {holdoutAdjusts}')


Época 1 finalizada. Pesos: [ -12.10997318  196.96314424 -222.10449475]
Época 2 finalizada. Pesos: [ -20.60997318  178.79623403 -223.38667824]
Época 3 finalizada. Pesos: [ -26.60997318  162.75295674 -223.19372556]
Época 4 finalizada. Pesos: [ -30.80997318  147.96579611 -222.3015852 ]
Época 5 finalizada. Pesos: [ -34.30997318  133.47797879 -221.30748611]
Época 6 finalizada. Pesos: [ -36.70997318  119.74358647 -220.0343783 ]
Época 7 finalizada. Pesos: [ -38.20997318  106.58601563 -218.60960755]
Época 8 finalizada. Pesos: [ -39.40997318   93.80470173 -217.05861466]
Época 9 finalizada. Pesos: [ -40.10997318   81.48765576 -215.40163141]
Época 10 finalizada. Pesos: [ -40.20997318   69.66979744 -213.66480158]
Época 11 finalizada. Pesos: [ -39.40997318   58.73568573 -211.80078376]
Época 12 finalizada. Pesos: [ -37.40997318   48.9325441  -209.84929258]
Época 13 finalizada. Pesos: [ -34.80997318   39.86269344 -207.83025301]
Época 14 finalizada. Pesos: [ -31.60997318   31.49720617 -205.7773103 ]
É